name: sbas_insar_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8 # Or 3.8 to match your ubuntu:20.04 apt python
  - mintpy
  - jupyter
  - notebook
  - dask
  - numpy
  - scipy
  - h5py
  - gdal # conda-forge gdal can be more robust than apt's
  - matplotlib
  - ipykernel # For Jupyter notebooks